### PR TITLE
Analytics implementation

### PR DESCRIPTION
**Pull request by donskov**
1. Add `telemetry` dialog.
image

2. Add `telemetry` option to the settings.
image

3. Add analytics to the application (`Mixpanel`).
4. Add missed locales translate.
5. Add a unique id for each user.
6. Improve application logging.

### CODE REVIEW

**Comment by donskov** [comment]
Don't forget to change the Mixpanel [token](https://github.com/PeculiarVentures/fortify/pull/374/files#diff-4b8706af41fcbb9d3bbbdfbe56504b5cce2a890cd8add8d320645ac916821d88R1) to production.

**Review by microshine — DISMISSED** [review]

**Comment by rmhrisk** [comment]
Usage and crash reports help us ensure future versions of Fortify address the issues you may experience. Leave usage and crash reporting enabled?

**Comment by rmhrisk** [comment]
And for the other one:
Usage and crash reports help us ensure future versions of Fortify address the issues you may experience. Do you want to enable usage and crash reporting?

**Comment by donskov** [comment]
@rmhrisk Thanks. After update:

image
image

**Pull request merged**
