### PR TITLE
WIP: Add GitHub actions

### LINKED ISSUE #305: Add support for other major distros
As of now, you only support Ubuntu on the linux front. Are you planning on supporting more linux distros (such as Fedora, CentOS, RHEL, openSUSE, SLES, Arch) ? 

You can also publish it as either a [snap package](https://snapcraft.io/docs/electron-apps) or a [flatpak](http://docs.flatpak.org/en/latest/electron.html). These two will make Fortify available to a variety of distros without needing to package separately for each of them

### PR DESCRIPTION
**Pull request by pkarakal**
This adds a configuration to build and package the application in all major platforms. GitHub in actions supports only windows, mac and linux. To build the application in other distributions, I have created Docker images that install the necessary dependencies, build the application and then on the distribution, it installs the necessary packages and runs the actual packaging of the application. (for the packaging electron installer was used). 

Under the config/ folder there are the necessary configuration files to run the packing and they also list the runtime dependencies of fortify. On ubuntu and debian, the packages are the same. Same goes for fedora and centos. openSUSE may use rpms to install packages but the dependencies there are somewhat different. 

The actual github ci yml resides under .github/workflows folder. There I am specifying that it should run on all tags, and under node 12 and 14 (lts and latest). From there it should run build and package the application, create a release for it, and also add artifacts to it. (The packages created from this pipeline) 

TODO: 
*  [ ]  Also publish installers from windows and macos and not only from ubuntu (and linux distros)
*  [x]  Optimize the Dockerfiles
*  [ ]  If signing the installer is something you want, maybe I can also work on that as well. 
*  [ ]  Do some tests on it. 
*  [ ]  (maybe) Add support for Arch and Arch-based linux distributions.

Closes #305

### CODE REVIEW

**Comment by pkarakal** [comment]
This is also blocked by #339 as installing it on linux currently fails

**Comment by pkarakal** [comment]
I have had a problem getting `fortify-prepare` installed in a docker environment and so the docker images cannot be built and fail at step 
```
RUN npm ci && npm install --save-dev electron-installer electron-installer-<input-distro-here> electron-packager
```

On my local machine I could get it to create and install an RPM file.

Help is more than welcome to get this up and running in a container.

**Comment by pkarakal** [comment]
I will lift temporarily the limitation on where the ci job can run , to test this feature end to end. I will revert that commit. Once I finish the tests, I will also work on squashing the commits and rebasing so that this can be reviewed.

**Comment by pkarakal** [comment]
I would like to ask anyone that knows, what dependencies are needed to build it on macos 

currently I have installed pcsc-lite, swig and OpenSC. Do I need to install something else? 

(I have the linux distros part working, and I just have to make it work on macos-latest and windows-latest)

**Comment by donskov** [comment]
Thanks, @pkarakal. We prepared our own CI setup.

**Pull request closed without merging**
